/*
 * async_i2c.c
 *
 *  Created on: 19 May 2026
 *      Author: vieth
 */

#include "async_i2c.h"
//#include "stm32f4xx_hal.h"   /* adjust to your MCU series */

#define SENSOR_I2C_ADDR   (0x19 << 1)   /* 7-bit addr shifted for HAL */

extern I2C_HandleTypeDef hi2c1;          /* generated by CubeMX */

/*===========================================================
 * PRIVATE TYPEDEFS
 *===========================================================*/
typedef void (*StepCb_t)(void);

typedef enum {
    STATE_TX_ADDR,   /* send register address byte */
    STATE_RX_DATA,   /* receive N data bytes       */
} ReadState_e;

/*===========================================================
 * MODULE GLOBALS  (the 3 pointers)
 *===========================================================*/
static SensorDoneCb_t  pDoneCb   = NULL;  /* user completion callback  */
static StepCb_t        pBusyFlag = NULL;  /* busy guard + re-entry cb  */
static StepCb_t        pHwCb     = NULL;  /* registered with HAL layer */

/* Working state for the current operation */
static uint8_t   g_regAddr;
static uint8_t  *g_outBuf;
static uint16_t  g_len;
static uint8_t   g_txBuf[1];   /* holds register address byte */

/*===========================================================
 * PROTORYPE DECLARATIONS
 *===========================================================*/
static void Sensor_ReadStep(void);
static void Sensor_Dispatcher(void);
static void Sensor_Complete(uint8_t result);

/*===========================================================
 * PUBLIC API
 *===========================================================*/
Result_e Sensor_ReadRegister(uint8_t regAddr, uint8_t *outBuf, uint16_t len,
                             SensorDoneCb_t doneCb)
{
	Result_e res = E_OK;
	if (pBusyFlag == NULL)
	{
		res = E_BUSY;
	} else {
		pBusyFlag = Sensor_ReadStep;  /* set busy flag and re-entry callback */
		pHwCb = Sensor_ReadStep;       /* set hardware callback to self */
	}
}

static void Sensor_ReadStep(void)
{
	/* Implementation of the state machine for the read operation */
	static ReadState_e state = STATE_TX_ADDR;
	switch (state)
	{
		case STATE_TX_ADDR:
			/*TODO*/
			if (E_OK == i2c_transmit_it()){
				/* Change next state for next process*/
				state = STATE_RX_DATA;
				/* set Fn Pointer to self function, 
				* make sure when IRQ fire, jump back to here -> next state*/
				pHwCb = Sensor_ReadStep;
			} else {
				/* do nothing, wait for next cycle*/
			}
			break;

		case STATE_RX_DATA:
			/*TODO*/
			if (E_OK == i2c_receive_it()){
				/* recive done, call completion callback */
				Sensor_Complete(E_OK);
			}
			break;
	}
}
